### ISSUE TITLE
todo... 

### ISSUE THREAD

**Issue by seoyoung-0** [seoyoung-0/CHECKU#4]
- [x] - abstractuser 로 변경 및 로그인 완료
- [x] - 구독 리스트에 추가
- [ ] - admin 의 Notice 모델 구독자들에 사용자 안 나오는거 해결 
- [x] - api key 분리해서 다시 import 하기 
- [ ] - 메일인증 수정 
- [ ] - 메일인증여부 확인해서 페이지 이동
